FROM node:10.16.1

COPY source/dist/. src/
WORKDIR /src
ENV MEMORY 1024
ENV API_PORT 8080
ENV ELASTICSEARCH_HOSTNAME elasticsearch
ENV ELASTICSEARCH_PORT 9200
ENV ELASTICSEARCH_PROTOCOL ELASTICSEARCH_PROTOCOL
ENV ELASTICSEARCH_INITIALIZE ELASTICSEARCH_INITIALIZE
ENV PLUMBER_PROTOCOL PLUMBER_PROTOCOL
ENV PLUMBER_HOSTNAME PLUMBER_HOSTNAME
ENV PLUMBER_PORT PLUMBER_PORT
ENV PLUMBER_RUNNER PLUMBER_RUNNER
ENV MAX_CONTENT_LENGTH MAX_CONTENT_LENGTH
ENV MAX_BODY_LENGTH MAX_BODY_LENGTH
CMD node --max-old-space-size=$MEMORY --optimize-for-size --inspect config/init/server.js
